### ISSUE TITLE
Movie browsing

### ISSUE THREAD

**Issue by Milofow** [Portfolio-Advanced-software/BingeBuster-WebUI#1]
<table>
  <thead>
    <tr>
      <td><b>Title:</b> <br>6. Movie browsing</td>
      <td><b>Priority:</b> <br> 5/5</td>
      <td><b>Estimate:</b> <br> - </td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan="3">
        <b>User Story:</b><br> 
        <b>As</b> a BingeBuster movie watcher, <br>
        <b>I want</b> to be able to get an overview of the available movies on the platform, <br>
        <b>so that</b> I can choose a movie to watch.</td>
    </tr>
    <tr>
      <td colspan="3">
        <b>Acceptance Criteria:</b><br>
          <ul>
            <li>While browsing I want to be able to search on titles</li>
            <li>While browsing I want to see the movie poster with it's name</li>
          </ul>
        </td>
    </tr>
  </tbody>
</table>

## Tasks
- [ ] Request to the Movie service to get all movies
- [ ] Show movies in grid format
- [ ] Show movie title, year, poster and play button
- [ ] Make movie clickable
